Repository nerds-and-company/schematic, pull requests merged in 2018-04, with the labels that each got.

#115 Make schematic a craft3 plugin
  README.md
  composer.json
  src/Schematic.php
Labels: wip

#116 Travis improvements
  .travis.yml
  composer.json
  src/Behaviors/FieldLayoutBehavior.php
  src/Controllers/ExportController.php
  src/Controllers/ImportController.php
  src/Converters/Models/Base.php
  src/Converters/Models/MatrixBlockType.php
  src/Converters/Models/UserGroup.php
  src/Mappers/ElementIndexMapper.php
  src/Mappers/ModelMapper.php
  src/Mappers/UserSettingsMapper.php
  tests/unit/Converters/Base/FieldTest.php
  tests/unit/Converters/Base/VolumeTest.php
  tests/unit/Converters/Elements/GlobalSetTest.php
  tests/unit/Converters/Models/AssetTransformTest.php
  tests/unit/Converters/Models/CategoryGroupTest.php
  tests/unit/Converters/Models/EntryTypeTest.php
  tests/unit/Converters/Models/MatrixBlockTypeTest.php
  tests/unit/Converters/Models/SectionTest.php
  tests/unit/Converters/Models/SiteTest.php
  tests/unit/Converters/Models/TagGroupTest.php
  tests/unit/Converters/Models/UserGroupTest.php
Labels: craft3, testable

#120 Improved metadata and added plugin icon
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  composer.json
  src/icon.svg
Labels: craft3, testable

#119 Added PHP 7.0 compatibility
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  CHANGELOG.md
  composer.json
  src/Controllers/Base.php
  src/Controllers/ImportController.php
  src/Converters/Fields/Assets.php
  src/Converters/Models/Base.php
  src/Interfaces/ConverterInterface.php
  src/Schematic.php
  src/icon.svg
Labels: craft3, testable

#124 Fixed a bug where fields weren't properly skipped when importing a se…
  CHANGELOG.md
  composer.json
  src/Converters/Base/Field.php
  src/Converters/Fields/Matrix.php
Labels: testable

#130 Don’t scrutinize test files
  .scrutinizer.yml
  .travis.yml
  codeception.yml
  phpmd.xml
Labels: testable

#131 Expanded field tests to include categories field source
  .scrutinizer.yml
  CHANGELOG.md
  composer.json
  tests/unit/Converters/Base/FieldTest.php
Labels: testable
